version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - node_modules:/workspace/node_modules
      - n8n_data:/workspace/n8n-data
    
    # ポート公開（Devcontainer内でn8nを起動するため）
    ports:
      - "5678:5678"  # n8n
      - "3000:3000"  # 開発用サーバー
      - "8080:8080"  # その他のサービス
    
    # 特権モードでDocker-in-Dockerを有効化
    privileged: true
    
    environment:
      - TZ=Asia/Tokyo
      - DOCKER_BUILDKIT=1
      - COMPOSE_DOCKER_CLI_BUILD=1
    
    # 常時起動
    tty: true
    stdin_open: true
    
    # Docker Composeネットワーク
    networks:
      - daily-collector-network

  # 本番用n8nサービス（開発時は無効化）
  # n8n:
  #   image: n8nio/n8n
  #   restart: unless-stopped
  #   ports:
  #     - "5678:5678"
  #   volumes:
  #     - n8n_data:/home/node/.n8n
  #   environment:
  #     - GENERIC_TIMEZONE=Asia/Tokyo
  #     - N8N_SECURE_COOKIE=false
  #   networks:
  #     - daily-collector-network

volumes:
  node_modules:
  n8n_data:

networks:
  daily-collector-network:
    driver: bridge
